### ISSUE TITLE
interception-tools package not found

### ISSUE THREAD

**Issue by ExMacro** [ugotapi/wayland-pagepi#2]
Hi!

I'm running a Raspberry Pi 4 with Debian Bullseye OS and trying to set up a kiosk mode with your code. Thanks for that! However, when installing
`sudo apt install -y interception-tools interception-tools-compat`
I get "E: Package interception-tools not found".

Any ideas? Thanks in advance!

**Comment by ExMacro** [comment]
Seems to work on the lates Raspberry Pi Bookworm.

**Comment by ugotapi** [comment]
Oh sorry about slow reply. Yes the latest version is what I use for these.
